### PR TITLE
cut new release

### PR DESCRIPTION
**Pull request by mrdaniellewis**

### CODE REVIEW

**Comment by mrdaniellewis** [comment]
Need to fix an issue with a hanging test. It will be 2 weeks before I can look at it.

**Comment by mrdaniellewis** [comment]
Need to fix an issue with a hanging test. It will be 2 weeks before I can look at it.

**Comment by luke-hill** [comment]
An agnostic way to do this is go to the end, press shift and home then backspace once.

See here: https://github.com/citizensadvice/design-system/blob/v4.1.0/testing/features/support/components/search/standard.rb#L20-L28 for how we did it on any desktop or device

Or you can use the option key which if on macs will work better

**Comment by mrdaniellewis** [comment]
I wasn't quite sure if the keyboard shortcuts for getting to the end of a text area are consistent across platforms.  It seems to be command + down on my mac.  Although shift + end also works, but just end doesn't.  But I won't know if the cursor is at the start or the end of the rich text as that seems to be a bit implementation specific on where is puts it.

I couldn't remember the shortcuts on windows.  I have this tiny concern it might even be different on linux although they mostly match windows if I recall right.

I think the control/meta + a shortcut is fairly well honoured, though.

I do feel there must be a better way.

**Comment by luke-hill** [comment]
Command+a / ctrl+a is a consistent way. Just needs the optional bit as you've coded.

But shift+home works universally by highlighting all the code then backspace to clear. Linux/Mac/Windows all works we've ran it at CA on the dockerised grids and on mac/windows/devices (Devices need to use backspace `n` times)

**Comment by mrdaniellewis** [comment]
The issue I had was, the cursor was unexpectedly at the start and not the end so it would be shift + end.  I'm not sure I can rely on where the cursor is.

**Comment by mrdaniellewis** [comment]
Oh well, this is working so I'm going to go with it for now.

**Comment by luke-hill** [comment]
If you press end then do shift and home, or vice versa you'd solve that niggle. But either way you're on it.

**Comment by mrdaniellewis** [comment]
Oh, I see what you mean 👍.  Yes, might change it to that at some point.

**Pull request merged**
